version: '3.8'

services:
  db:
    image: postgres:15
    container_name: smart_appointment_db
    restart: always
    environment:
      POSTGRES_USER: smart-appointment-user
      POSTGRES_PASSWORD: smart-appointment-pass
      POSTGRES_DB: smart-appointment-db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
